#!/bin/bash
#SBATCH -n 4  # number of cores
#SBATCH -t 0-12:00  # Runtime DAYS-HRS:MIN
#SBATCH -p sched_mit_hill  # Node partition, don't change this
#SBATCH --mem-per-cpu=4000  # Request 4G of memory per CPU
#SBATCH -o out_%A_%a.txt  # Redirect output to output_JOBID.txt
#SBATCH -e err_%A_%a.txt  # Redirect errors to error_JOBID.txt
#SBATCH --mail-type=END  # Mail when job ends
#SBATCH --mail-user=lujz@mit.edu  # Email recipient

source activate myenv
echo "Hello World"
python commuting.py -m 150 -n 50 -k 6 --trials 1 -d --key $SLURM_ARRAY_TASK_ID
echo "Done!"